spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost/jpa1
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true #??? ??

springdoc:
  swagger-ui:
    path: /swagger.html
